### ISSUE TITLE
Add a label for the radio type inside the marker

### ISSUE THREAD

**Issue by Gitschubser** [Rudloff/mls-cell-map#22]
I dont know if this is possible but i describe it what i mean.
Is it possible to add a text, a label, a .png inside the marker with the label 2G, 3G, ... to distinguish between the different radio types GSM, UMTS, LTE and CDMA in the map?

**Comment by Rudloff** [comment]
I added the first letter of the radio type. Is that understandable enough?

**Comment by Gitschubser** [comment]
Wow, very cool. Thanks. 
It is understandable enough. 
Maybe for all visitors is a legend interesting (Example on the right at www.openstreetmap.org -> i)?

G = GSM
U = UMTS
....
