### ISSUE TITLE
Issue: Missing marker where "Type" has no value 

### ISSUE THREAD

**Issue by Gitschubser** [Rudloff/mls-cell-map#27]
In the map have some markers no "Type" and are not drawn on them map correctly.

**Comment by Gitschubser** [comment]
I know the issue. Mozilla Location Service changed the name in the file from the cells with type UMTS to WCDMA!
Your map doesnt show the marker with UMTS (not type WCDMA).
Thats the issue.

**Comment by Gitschubser** [comment]
https://github.com/mozilla/ichnaea/issues/457

**Comment by Rudloff** [comment]
You're right, thanks for the info!

**Comment by Gitschubser** [comment]
WCDMA has been replaced by UMTS.
MLS changed it back.
UMTS,724,2,51321,138528246,344,-43.4069454,-22.9777784,232,5,1,1442677561,1443780175
