### ISSUE TITLE
Similar map for OpenCelliD

### ISSUE THREAD

**Issue by gopi-ar** [Rudloff/mls-cell-map#34]
Hello!

My company Unwired is the new maintainer of OCID; we absolutely love your map and were wondering if you could maintain a new repo for OCID data as well? Our community has been asking for such a map for coverage and quick searches and since community effort has already gone into this project, it'd be awesome if you guys could adapt it to accept OCID data..

We'll of course include attributions and link-backs when we put this up on the main website.

Cheers,
Gopi

**Comment by Rudloff** [comment]
Hello,
Instead of a separate repository, I would prefer to add some config that allows to choose which data source to use.
OCID used to have a CSV export very similar to the one provided by MLS but I can't find it anymore. Do you still provide these?

**Comment by gopi-ar** [comment]
We still provide these, they're available either via the Downloads tab after login or at this URL:
https://download.unwiredlabs.com/ocid/downloads?token=YOUR_TOKEN_HERE&file=cell_towers.csv.gz

**Comment by Rudloff** [comment]
I refactored the import script on the develop branch, then added an option to use OCID data: bbaf27b8d22bab9568b9cc094c6edc564f44f7dc
It is briefly explained in the README: https://github.com/Rudloff/mls-cell-map/blob/develop/README.md#opencellid

Please tell me if you need anything else.

**Comment by gopi-ar** [comment]
This is great, we'll link-back shortly from the website!

Any thoughts on displaying the world coverage map in clusters without crashing the browser or network? The old OCID code did do this with summaries but we were thinking of incorporating your map so any ideas on scaling it to higher zoom levels would be appreciated..

**Comment by Rudloff** [comment]
I would recommend displaying only your coverage raster layer at lower zoom levels and adding the markers only when zoomed enough.

**Comment by Rudloff** [comment]
@gopi-ar Did you need anything else about this?

**Comment by gopi-ar** [comment]
No, thank you for your support!
